[PIO-57] Add SBT Native Packager
Closes #359

diff --git a/bin/pio b/bin/pio
--- a/bin/pio
+++ b/bin/pio
@@ -32,28 +32,38 @@ search() {
   echo ${i}
 }
 
-PIO_FILE=$(readlink -f $0 2>/dev/null)
-if [ $? = 0 ] ; then 
-  export PIO_HOME="$(cd $(dirname $PIO_FILE)/..; pwd)"
-else
-  CURRENT_DIR=`pwd`
-  TARGET_FILE="$0"
-  cd "$(dirname "$TARGET_FILE")"
-  TARGET_FILE=$(basename "$TARGET_FILE")
-
-  while [ -L "$TARGET_FILE" ]
-  do
-    TARGET_FILE=$(readlink "$TARGET_FILE")
+if [ -z $PIO_HOME ] ; then
+  PIO_FILE=$(readlink -f $0 2>/dev/null)
+  if [ $? = 0 ] ; then
+    export PIO_HOME="$(cd $(dirname $PIO_FILE)/..; pwd)"
+  else
+    CURRENT_DIR=`pwd`
+    TARGET_FILE="$0"
     cd "$(dirname "$TARGET_FILE")"
     TARGET_FILE=$(basename "$TARGET_FILE")
-  done
 
-  export PIO_HOME="$(cd $(dirname "$TARGET_FILE")/..; pwd -P)"
-  cd "$CURRENT_DIR"
+    while [ -L "$TARGET_FILE" ]
+    do
+      TARGET_FILE=$(readlink "$TARGET_FILE")
+      cd "$(dirname "$TARGET_FILE")"
+      TARGET_FILE=$(basename "$TARGET_FILE")
+    done
+
+    export PIO_HOME="$(cd $(dirname "$TARGET_FILE")/..; pwd -P)"
+    cd "$CURRENT_DIR"
+  fi
 fi
 
-
-export PIO_CONF_DIR="${PIO_HOME}/conf"
+if [ -z $PIO_CONF_DIR ] ; then
+  export PIO_CONF_DIR="${PIO_HOME}/conf"
+  if [ ! -d $PIO_CONF_DIR ] ; then
+    export PIO_CONF_DIR="/etc/predictionio"
+    if [ ! -d $PIO_CONF_DIR ] ; then
+      echo "PIO_CONF_DIR is not found."
+      exit 1
+    fi
+  fi
+fi
 
 FIRST_SEP=$(search "--" $@)
 
diff --git a/bin/pio-class b/bin/pio-class
--- a/bin/pio-class
+++ b/bin/pio-class
@@ -40,8 +40,8 @@ if [ -z "$1" ]; then
 fi
 
 # Warn if log4j.properties is not present
-if [ ! -f "$FWDIR/conf/log4j.properties" ]; then
-  echo -e "\033[0;35mWarning: log4j.properties is missing from $FWDIR/conf\033[0m"
+if [ ! -f "$PIO_CONF_DIR/log4j.properties" ]; then
+  echo -e "\033[0;35mWarning: log4j.properties is missing from $PIO_CONF_DIR\033[0m"
 fi
 
 # Make sure the Apache Spark version meets the prerequisite if it is a binary
@@ -84,6 +84,19 @@ else
   CLASSPATH=${classpath_output}
 fi
 
+if [ -z $PIO_LOG_DIR ] ; then
+  PIO_LOG_DIR=$PIO_HOME/log
+  touch $PIO_LOG_DIR/pio.log > /dev/null 2>&1
+  if [ $? != 0 ] ; then
+    PIO_LOG_DIR=/var/log/predictionio
+    touch $PIO_LOG_DIR/pio.log > /dev/null 2>&1
+    if [ $? != 0 ] ; then
+      PIO_LOG_DIR=$HOME
+    fi
+  fi
+fi
+
 export CLASSPATH
+export JAVA_OPTS="$JAVA_OPTS -Dpio.log.dir=$PIO_LOG_DIR"
 
 exec "$RUNNER" -cp "$CLASSPATH" $JAVA_OPTS "$@"
diff --git a/bin/pio-start-all b/bin/pio-start-all
--- a/bin/pio-start-all
+++ b/bin/pio-start-all
@@ -25,63 +25,78 @@ export PIO_HOME="$(cd `dirname $0`/..; pwd)"
 
 . ${PIO_HOME}/bin/load-pio-env.sh
 
+SOURCE_TYPE=$PIO_STORAGE_REPOSITORIES_METADATA_SOURCE
+SOURCE_TYPE=$SOURCE_TYPE$PIO_STORAGE_REPOSITORIES_EVENTDATA_SOURCE
+SOURCE_TYPE=$SOURCE_TYPE$PIO_STORAGE_REPOSITORIES_MODELDATA_SOURCE
+
 # Elasticsearch
-echo "Starting Elasticsearch..."
-if [ -n "$PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME" ]; then
-  if [ -n "$JAVA_HOME" ]; then
-    JPS=`$JAVA_HOME/bin/jps`
-  else
-    JPS=`jps`
+if [ `echo $SOURCE_TYPE | grep -i elasticsearch | wc -l` != 0 ] ; then
+  echo "Starting Elasticsearch..."
+  if [ -n "$PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME" ]; then
+    ELASTICSEARCH_HOME=$PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME
+  elif [ -n "$PIO_STORAGE_SOURCES_ELASTICSEARCH5_HOME" ]; then
+    ELASTICSEARCH_HOME=$PIO_STORAGE_SOURCES_ELASTICSEARCH5_HOME
   fi
-  if [[ ${JPS} =~ "Elasticsearch" ]]; then
-    echo -e "\033[0;31mElasticsearch is already running. Please use pio-stop-all to try stopping it first.\033[0m"
-    echo -e "\033[0;31mNote: If you started Elasticsearch manually, you will need to kill it manually.\033[0m"
-    echo -e "\033[0;31mAborting...\033[0m"
+  if [ -n "$ELASTICSEARCH_HOME" ]; then
+    if [ -n "$JAVA_HOME" ]; then
+      JPS=`$JAVA_HOME/bin/jps`
+    else
+      JPS=`jps`
+    fi
+    if [[ ${JPS} =~ "Elasticsearch" ]]; then
+      echo -e "\033[0;31mElasticsearch is already running. Please use pio-stop-all to try stopping it first.\033[0m"
+      echo -e "\033[0;31mNote: If you started Elasticsearch manually, you will need to kill it manually.\033[0m"
+      echo -e "\033[0;31mAborting...\033[0m"
+      exit 1
+    else
+      $ELASTICSEARCH_HOME/bin/elasticsearch -d -p $PIO_HOME/es.pid
+    fi
+  else
+    echo -e "\033[0;31mPlease set PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME in conf/pio-env.sh, or in your environment.\033[0m"
+    echo -e "\033[0;31mCannot start Elasticsearch. Aborting...\033[0m"
     exit 1
-  else
-    $PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME/bin/elasticsearch -d -p $PIO_HOME/es.pid
   fi
-else
-  echo -e "\033[0;31mPlease set PIO_STORAGE_SOURCES_ELASTICSEARCH_HOME in conf/pio-env.sh, or in your environment.\033[0m"
-  echo -e "\033[0;31mCannot start Elasticsearch. Aborting...\033[0m"
-  exit 1
 fi
 
 # HBase
-echo "Starting HBase..."
-if [ -n "$PIO_STORAGE_SOURCES_HBASE_HOME" ]; then
-  $PIO_STORAGE_SOURCES_HBASE_HOME/bin/start-hbase.sh
-else
-  echo -e "\033[0;31mPlease set PIO_STORAGE_SOURCES_HBASE_HOME in conf/pio-env.sh, or in your environment.\033[0m"
-  # Kill everything for cleanliness
-  echo -e "\033[0;31mCannot start HBase. Aborting...\033[0m"
-  sleep 3
-  ${PIO_HOME}/bin/pio-stop-all
-  exit 1
-fi
-
-#PGSQL
-pgsqlStatus="$(ps auxwww | grep postgres | wc -l)"
-if [[ "$pgsqlStatus" < 5 ]]; then
-  # Detect OS
-  OS=`uname`
-  if [[ "$OS" = "Darwin" ]]; then
-    pg_cmd=`which pg_ctl`
-    if [[ "$pg_cmd" != "" ]]; then
-      pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
-    fi
-  elif [[ "$OS" = "Linux" ]]; then
-    sudo service postgresql start
+if [ `echo $SOURCE_TYPE | grep -i hbase | wc -l` != 0 ] ; then
+  echo "Starting HBase..."
+  if [ -n "$PIO_STORAGE_SOURCES_HBASE_HOME" ]; then
+    $PIO_STORAGE_SOURCES_HBASE_HOME/bin/start-hbase.sh
   else
-    echo -e "\033[1;31mYour OS $OS is not yet supported for automatic postgresql startup:(\033[0m"
-    echo -e "\033[1;31mPlease do a manual startup!\033[0m"
+    echo -e "\033[0;31mPlease set PIO_STORAGE_SOURCES_HBASE_HOME in conf/pio-env.sh, or in your environment.\033[0m"
+    # Kill everything for cleanliness
+    echo -e "\033[0;31mCannot start HBase. Aborting...\033[0m"
+    sleep 3
     ${PIO_HOME}/bin/pio-stop-all
     exit 1
   fi
 fi
 
+#PGSQL
+if [ `echo $SOURCE_TYPE | grep -i pgsql | wc -l` != 0 ] ; then
+  pgsqlStatus="$(ps auxwww | grep postgres | wc -l)"
+  if [[ "$pgsqlStatus" < 5 ]]; then
+    # Detect OS
+    OS=`uname`
+    if [[ "$OS" = "Darwin" ]]; then
+      pg_cmd=`which pg_ctl`
+      if [[ "$pg_cmd" != "" ]]; then
+        pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
+      fi
+    elif [[ "$OS" = "Linux" ]]; then
+      sudo service postgresql start
+    else
+      echo -e "\033[1;31mYour OS $OS is not yet supported for automatic postgresql startup:(\033[0m"
+      echo -e "\033[1;31mPlease do a manual startup!\033[0m"
+      ${PIO_HOME}/bin/pio-stop-all
+      exit 1
+    fi
+  fi
+fi
+
 # PredictionIO Event Server
-echo "Waiting 10 seconds for HBase to fully initialize..."
+echo "Waiting 10 seconds for Storage Repositories to fully initialize..."
 sleep 10
 echo "Starting PredictionIO Event Server..."
 ${PIO_HOME}/bin/pio-daemon ${PIO_HOME}/eventserver.pid eventserver --ip 0.0.0.0
